### PR TITLE
Load all cloud variables on session instead of using the onload function

### LINKED ISSUE #13: Instead of using onload for cloud variable loading, wait a couple of milliseconds on session.
To load every cloud variable, you have to use the onload function. However, instead of doing this, it would be better just to wait a couple of milliseconds when a session has been created.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #13 

Notes: You can go as low as 80 milliseconds, however, 500 milliseconds will work. It's been tested and all variables load every time. I bumped to 1.4.0 because it fixes a bug and makes a fix (#12) better.

### CODE REVIEW

**Comment by AmazingMech2418** [comment]
High internet latency will take longer than 500 milliseconds. Often it takes a few seconds normally anyways. I don't think this would work really, especially if there are the full 10 variables in the project.

**Comment by ghost** [comment]
I have tested around 45 times with 10 cloud variables. My internet speed is around ~0 Mbps, and all cloud variables have returned every time. It seems to work perfectly fine.

**Comment by ghost** [comment]
@AmazingMech2418

**Comment by AmazingMech2418** [comment]
This is not the ideal fix. I think the onload function works perfectly fine.

**Pull request closed without merging**
